version: '3.8'

services:
  bgclean:
    build: .
    ports:
      - "80:7860"  # Map to standard HTTP port
    environment:
      - PORT=7860
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - model_cache:/root/.u2net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bgclean
    restart: always
    profiles:
      - proxy

volumes:
  model_cache: 