version: '3.8'

services:
  bgclean-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - model_cache:/root/.u2net
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model_cache: 